### ISSUE TITLE
Issue with Polyhedron

### ISSUE THREAD

**Issue by JiangLin-Lan** [mahyarfazlyab/ReachSDP#1]
Hello,

I tried to run the code on MATLAB R2020b. But it returned the following error:

Check for missing argument or incorrect argument data type in call to function 'Polyhedron'.

Error in main (line 59)
X0_poly = Polyhedron([1 0; -1 0; 0 1; 0 -1], X0_b);

Any idea on addressing this issue? Did you use a customalised function Polyhedron? 

Thanks for help!

**Comment by HaiminClack** [comment]
Hi, the `Polyhedron` function is part of the [MPT3 toolbox](https://www.mpt3.org/). Please install it first. Thanks!

**Comment by JiangLin-Lan** [comment]
Issue resolved after installing MPT3 toolbox. Thanks.
